version: '2'
services:
  lb:
    image: rancher/lb-service-haproxy:v0.9.1
    ports:
      - 8089:80/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin, agent
      io.rancher.container.agent_service.draint_provider: 'true'
      io.rancher.container.create_agent: 'true'
  dns:
    image: steamcache/steamcache-dns:latest
    ports:
      - 53:53/udp
    environment:
      CACHE_IP=${CACHE_IP}
  sni-proxy:
    image: steamcache/sni-proxy:latest
    ports:
        - 443:443/tcp

  blizzard:
    image: steamcache/generic:latest
    volumes:
      - ${CACHE_ROOT}/blizzard/data:/data/cache
      - ${CACHE_ROOT}/blizzard/logs:/data/logs

  frontier:
    image: steamcache/generic:latest
    volumes:
      - ${CACHE_ROOT}/frontier/data:/data/cache
      - ${CACHE_ROOT}/frontier/logs:/data/logs

  origin:
    image: steamcache/generic:latest
    volumes:
      - ${CACHE_ROOT}/origin/data:/data/cache
      - ${CACHE_ROOT}/origin/logs:/data/logs

  riot:
    image: steamcache/generic:latest
    volumes:
      - ${CACHE_ROOT}/riot/data:/data/cache
      - ${CACHE_ROOT}/riot/logs:/data/logs

  steamcache:
    image: steamcache/steamcache:latest
    volumes:
      - ${CACHE_ROOT}/steam/data:/data/cache
      - ${CACHE_ROOT}/steam/logs:/data/logs

  uplay:
    image: steamcache/generic:latest
    volumes:
      - ${CACHE_ROOT}/uplay/data:/data/cache
      - ${CACHE_ROOT}/uplay/logs:/data/logs

  windows:
    image: steamcache/generic:latest
    volumes:
      - ${CACHE_ROOT}/windows/data:/data/cache
      - ${CACHE_ROOT}/windows/logs:/data/logs

