version: '2'

catalog:

    name: lancache-fullstack
    version: 1.0.0
    description: "Full LAN Caching stack for Blizzard, Frontier, Origin, Riot, Steam, Uplay and Windows Updates"
    questions:
        - variable: CACHE_ROOT
          label: Cache directory (This should be available on ALL hosts that the caching servers will be running on.
          required: true
          type: string
        - variable: CACHE_IP
          label: Cache IP Address
          default: 10.0.0.1
          required: true
          type: string
services:
  dns:
    scale: 1
    start_on_create: true

  sni-proxy:
    scale: 1
    start_on_create: true

  blizzard:
    scale: 1
    start_on_create: true

  frontier:
    scale: 1
    start_on_create: true

  origin:
    scale: 1
    start_on_create: true

  riot:
    scale: 1
    start_on_create: true

  steam:
    scale: 1
    start_on_create: true

  uplay:
    scale: 1
    start_on_create: true

  windows:
    scale: 1
    start_on_create: true
  lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - hostname: '*.content.steampowered.com'
        path: ''
        priority: 1
        protocol: http
        service: steam
        source_port: 80
        target_port: 80
      - hostname: 'content1.steampowered.com'
        path: ''
        priority: 1
        protocol: http
        service: steam
        source_port: 80
        target_port: 80
      - hostname: 'content2.steampowered.com'
        path: ''
        priority: 1
        protocol: http
        service: steam
        source_port: 80
        target_port: 80
      - hostname: 'content3.steampowered.com'
        path: ''
        priority: 1
        protocol: http
        service: steam
        source_port: 80
        target_port: 80
      - hostname: 'content4.steampowered.com'
        path: ''
        priority: 1
        protocol: http
        service: steam
        source_port: 80
        target_port: 80
      - hostname: 'content5.steampowered.com'
        path: ''
        priority: 1
        protocol: http
        service: steam
        source_port: 80
        target_port: 80
      - hostname: 'content6.steampowered.com'
        path: ''
        priority: 1
        protocol: http
        service: steam
        source_port: 80
        target_port: 80
      - hostname: 'content7.steampowered.com'
        path: ''
        priority: 1
        protocol: http
        service: steam
        source_port: 80
        target_port: 80
      - hostname: 'content8.steampowered.com'
        path: ''
        priority: 1
        protocol: http
        service: steam
        source_port: 80
        target_port: 80
      - hostname: 'cs.steampowered.com'
        path: ''
        priority: 1
        protocol: http
        service: steam
        source_port: 80
        target_port: 80
      - hostname: 'steamcontent.com'
        path: ''
        priority: 1
        protocol: http
        service: steam
        source_port: 80
        target_port: 80
      - hostname: 'client-download.steampowered.com'
        path: ''
        priority: 1
        protocol: http
        service: steam
        source_port: 80
        target_port: 80
      - hostname: '*.hsar.steampowered.com.edgesuite.net'
        path: ''
        priority: 1
        protocol: http
        service: steam
        source_port: 80
        target_port: 80
      - hostname: '*.akamai.steamstatic.com'
        path: ''
        priority: 1
        protocol: http
        service: steam
        source_port: 80
        target_port: 80
      - hostname: 'content-origin.steampowered.com'
        path: ''
        priority: 1
        protocol: http
        service: steam
        source_port: 80
        target_port: 80
      - hostname: 'clientconfig.akamai.steamtransparent.com'
        path: ''
        priority: 1
        protocol: http
        service: steam
        source_port: 80
        target_port: 80
      - hostname: 'steampipe.akamaized.net'
        path: ''
        priority: 1
        protocol: http
        service: steam
        source_port: 80
        target_port: 80
      - hostname: 'edgecast.steamstatic.com'
        path: ''
        priority: 1
        protocol: http
        service: steam
        source_port: 80
        target_port: 80
      - hostname: 'steam.apac.qtlglb.com.mwcloudcdn.com'
        path: ''
        priority: 1
        protocol: http
        service: steam
        source_port: 80
        target_port: 80
      - hostname: '*.cs.steampowered.com'
        path: ''
        priority: 1
        protocol: http
        service: steam
        source_port: 80
        target_port: 80
      - hostname: '*.edgecast.steamstatic.com'
        path: ''
        priority: 1
        protocol: http
        service: steam
        source_port: 80
        target_port: 80
      - hostname: '*.steamcontent.com'
        path: ''
        priority: 1
        protocol: http
        service: steam
        source_port: 80
        target_port: 80
      - hostname: 'cdn1-sea1.valve.net'
        path: ''
        priority: 1
        protocol: http
        service: steam
        source_port: 80
        target_port: 80
      - hostname: 'cdn2-sea1.valve.net'
        path: ''
        priority: 1
        protocol: http
        service: steam
        source_port: 80
        target_port: 80
      - hostname: '*.steam-content-dnld-1.apac-1-cdn.cqloud.com'
        path: ''
        priority: 1
        protocol: http
        service: steam
        source_port: 80
        target_port: 80
