version: '2'

catalog:

    name: lancache-fullstack
    version: 1.0.0
    description: "Full LAN Caching stack for Blizzard, Frontier, Origin, Riot, Steam, Uplay and Windows Updates"
    questions:
        - variable: CACHE_ROOT
          label: Cache directory (This should be available on ALL hosts that the caching servers will be running on.
          required: true
          type: string
        - variable: BLIZZARDCACHE_IP
          label: Blizzard IP Address
          default: 10.0.0.1
          required: true
          type: string
        - variable: FRONTIERCACHE_IP
          label: Frontier IP Address
          default: 10.0.0.2
          required: true
          type: string
        - variable: ORIGINCACHE_IP
          label: Origin IP Address
          default: 10.0.0.3
          required: true
          type: string
        - variable: RIOTCACHE_IP
          label: RIOT IP Address
          default: 10.0.0.4
          required: true
          type: string
        - variable: STEAMCACHE_IP
          label: Steam IP Address
          default: 10.0.0.5
          required: true
          type: string
        - variable: UPLAYCACHE_IP
          label: Uplay IP Address
          default: 10.0.0.6
          required: true
          type: string
        - variable: WINDOWSCACHE_IP
          label: Windows IP Address
          default: 10.0.0.7
          required: true
          type: string

services:
  dns:
    scale: 1
    start_on_create: true

  sni-proxy:
    scale: 1
    start_on_create: true

  blizzard:
    scale: 1
    start_on_create: true

  frontier:
    scale: 1
    start_on_create: true

  origin:
    scale: 1
    start_on_create: true

  riot:
    scale: 1
    start_on_create: true

  steam:
    scale: 1
    start_on_create: true

  uplay:
    scale: 1
    start_on_create: true

  windows:
    scale: 1
    start_on_create: true

