version: '2'
services:
  sni-proxy:
    image: steamcache/sni-proxy:latest
    ports:
        - 443:443/tcp

  blizzard:
    image: steamcache/generic:latest
    volumes:
      - ${CACHE_ROOT}/blizzard/data:/data/cache
      - ${CACHE_ROOT}/blizzard/logs:/data/logs
    ports:
      - ${BLIZZARDCACHE_IP}:80:80/tcp

  frontier:
    image: steamcache/generic:latest
    volumes:
      - ${CACHE_ROOT}/frontier/data:/data/cache
      - ${CACHE_ROOT}/frontier/logs:/data/logs
    ports:
      - ${FRONTIER_IP}:80:80/tcp

  origin:
    image: steamcache/generic:latest
    volumes:
      - ${CACHE_ROOT}/origin/data:/data/cache
      - ${CACHE_ROOT}/origin/logs:/data/logs
    ports:
      - ${ORIGINCACHE_IP}:80:80/tcp

  riot:
    image: steamcache/generic:latest
    volumes:
      - ${CACHE_ROOT}/riot/data:/data/cache
      - ${CACHE_ROOT}/riot/logs:/data/logs
    ports:
      - ${RIOTCACHE_IP}:80:80/tcp

  steamcache:
    image: steamcache/steamcache:latest
    volumes:
      - ${CACHE_ROOT}/steam/data:/data/cache
      - ${CACHE_ROOT}/steam/logs:/data/logs
    ports:
      - ${STEAMCACHE_IP}:80:80/tcp

  uplay:
    image: steamcache/generic:latest
    volumes:
      - ${CACHE_ROOT}/uplay/data:/data/cache
      - ${CACHE_ROOT}/uplay/logs:/data/logs
    ports:
      - ${UPLAYCACHE_IP}:80:80/tcp

  windows:
    image: steamcache/generic:latest
    volumes:
      - ${CACHE_ROOT}/windows/data:/data/cache
      - ${CACHE_ROOT}/windows/logs:/data/logs
    ports:
      - ${WINDOWSCACHE_IP}:80:80/tcp

